hub: "ghcr.io/alexanderakulshin"
image: "test_task"
tag: "0.1.0"

imagePullPolicy: IfNotPresent
imagePullSecrets: []

prod: false

env:
  FOO: "bar"
  LOG_LEVEL: "debug"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8080
  annotations: {}

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

affinity:
  podAntiAffinity:
    enabled: true
    type: preferred

topologySpreadConstraints:
  enabled: true
  whenUnsatisfiable: ScheduleAnyway
  topologyKey: "kubernetes.io/hostname"
  maxSkew: 1

pdb:
  enabled: true
  minAvailable: 2

networkPolicy:
  enabled: true
  allowIngressFromSameNamespace: true
  allowAllEgress: true
