---
# Source: internal-service/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: isvc-dev-internal-service
  labels:
    app.kubernetes.io/name: internal-service
    app.kubernetes.io/instance: isvc-dev
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: web
