resources:
  - ../../base
namePrefix: prod-
labels:
  - includeSelectors: true
    pairs:
      env: prod
patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=internal-service"
    path: patch-deployment.yaml
  - target:
      kind: HorizontalPodAutoscaler
      labelSelector: "app.kubernetes.io/name=internal-service"
    path: patch-hpa.yaml