apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-used
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: PROD
              value: "false"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"