{{- if and .Values.pdb.enabled (.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "internal-service.fullname" . }}
  labels:
    {{- include "internal-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "internal-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
